// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZTMNItDvDizDC_vGnzZnGtY9nbTTme-E',
    appId: '1:476036467149:web:3c2ce107e713d491c91c84',
    messagingSenderId: '476036467149',
    projectId: 'fashionapp-e783f',
    authDomain: 'fashionapp-e783f.firebaseapp.com',
    storageBucket: 'fashionapp-e783f.firebasestorage.app',
    measurementId: 'G-5REVQQMHEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXL_cglyqeXwVDmujI1-UJXvgYbqNXrX8',
    appId: '1:476036467149:android:16de3d9b6f4a201dc91c84',
    messagingSenderId: '476036467149',
    projectId: 'fashionapp-e783f',
    storageBucket: 'fashionapp-e783f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfmaRnnkFlPvrwCvayMM93-1aGbGVfeE',
    appId: '1:476036467149:ios:ecb443e272461ccec91c84',
    messagingSenderId: '476036467149',
    projectId: 'fashionapp-e783f',
    storageBucket: 'fashionapp-e783f.firebasestorage.app',
    iosBundleId: 'com.example.fashionn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADfmaRnnkFlPvrwCvayMM93-1aGbGVfeE',
    appId: '1:476036467149:ios:a89ea21a534ef873c91c84',
    messagingSenderId: '476036467149',
    projectId: 'fashionapp-e783f',
    storageBucket: 'fashionapp-e783f.firebasestorage.app',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZTMNItDvDizDC_vGnzZnGtY9nbTTme-E',
    appId: '1:476036467149:web:fe0787e2f4271b54c91c84',
    messagingSenderId: '476036467149',
    projectId: 'fashionapp-e783f',
    authDomain: 'fashionapp-e783f.firebaseapp.com',
    storageBucket: 'fashionapp-e783f.firebasestorage.app',
    measurementId: 'G-YWR30W0CKT',
  );
}
